; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<main>
monitor_speed = 115200

[env:Devices-MOTOR]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<main/devices/motor>
monitor_speed = 112500
lib_deps = 

[env:Devices-ENCODER]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<devices/encoder>
monitor_speed = 112500
lib_deps = 

[env:Devices-FIM]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<devices/fim>
monitor_speed = 112500
lib_deps = 

[env:Devices-TELA]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<devices/tela>
monitor_speed = 112500
lib_deps = 

[env:Devices-BOTOES]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<devices/botoes>
monitor_speed = 112500
lib_deps =